### ISSUE TITLE
Use of `link-cplusplus` forces use of shared C++ Stdlib on Android.

### ISSUE THREAD

**Issue by johnoneil** [dtolnay/link-cplusplus#12]
I've picked up a dependency on `link-cplusplus` via use of `autocxx` (which in turn uses `cxx`).

I'm therefore having difficulty controlling the behavior of `link-cplusplus` in the following ways:

For some reason, under android builds, the build of `link-cplusplus` is bringing in the `c++_shared` version of the C++stdlib, while I would like to use `c++_static`. Here's a verbose log of the crate build (note the last line):
```
[link-cplusplus 1.0.9] exit status: 0
[link-cplusplus 1.0.9] running: "llvm-ar" "s" ".../build/link-cplusplus-d9a0ba33ab9616c9/out/liblink-cplusplus.a"
[link-cplusplus 1.0.9] exit status: 0
[link-cplusplus 1.0.9] cargo:rustc-link-lib=static=link-cplusplus
[link-cplusplus 1.0.9] cargo:rustc-link-search=native=.../target/aarch64-linux-android/release/build/link-cplusplus-d9a0ba33ab9616c9/out
[link-cplusplus 1.0.9] cargo:rerun-if-env-changed=CXXSTDLIB_aarch64-linux-android
[link-cplusplus 1.0.9] CXXSTDLIB_aarch64-linux-android = None
[link-cplusplus 1.0.9] cargo:rerun-if-env-changed=CXXSTDLIB_aarch64_linux_android
[link-cplusplus 1.0.9] CXXSTDLIB_aarch64_linux_android = None
[link-cplusplus 1.0.9] cargo:rerun-if-env-changed=TARGET_CXXSTDLIB
[link-cplusplus 1.0.9] TARGET_CXXSTDLIB = None
[link-cplusplus 1.0.9] cargo:rerun-if-env-changed=CXXSTDLIB
[link-cplusplus 1.0.9] CXXSTDLIB = None
[link-cplusplus 1.0.9] cargo:rustc-link-lib=c++_shared <------ NOTE. Where is this coming from?
```

So I guess my questions are:

* If my dependency on `link-cplusplus` is several steps removed from my application, how can I control its behavior (i.e. turn on and of features) ?
* More importantly, how can I change its behavior so as to not use the `c++_shared` version of the C++ stdlib under android builds.

I don't believe the above will entirely solve my problems but they might help move things forward.

**Comment by johnoneil** [comment]
I think my questions above are still valid, but my need for info in this area kind of went away, as I found some alternate approaches.

I'm going to close this as it's not really needed currently.

**Comment by OxygenCobalt** [comment]
This is still relevant for me, I really want to statically link for my android app and avoid the 4mb binary size hit caused by using the unoptimized shared version.

**Comment by OxygenCobalt** [comment]
This is still relevant for me, I really want to statically link for my android app and avoid the 4mb binary size hit caused by using the unoptimized shared version.

Can anything be done @dtolnay?

**Comment by dtolnay** [comment]
I don't know much about Android but I would be interested to see a PR if you have a better idea.

**Comment by OxygenCobalt** [comment]
So, I looked into it @dtolnay and found that adding link_cplusplus:

```
link-cplusplus = {version = "1.0.9", features = ["nothing"]
```

And manually trying to statically link c++_shared prevents the .so from explicitly requiring libc++_shared (i.e it's no longer NEEDED in the ELF), but then for some reason it still transitively requires it and I frankly cant tell why at all. This only happens when cxx is added as far as I'm aware. Where else could cxx possibly be transitively linking into c++_shared??

Here is my jank link code:

```
    println!(
        "cargo:rustc-link-search=native={}/lib",
        arch_pkg_dir.display()
    );
    println!("cargo:rustc-link-lib=static=tag");
    println!("cargo:rustc-link-lib=static=c++_static");
    println!("cargo:rustc-link-lib=static=c++abi");
    println!("cargo:rustc-link-lib=static=unwind");
    // println!("cargo:rustc-link-lib=cc++_static");

    // Build the shim and cxx bridge together
    let mut builder = cxx_build::bridge("src/taglib/bridge.rs");
    builder
        .file("shim/iostream_shim.cpp")
        .file("shim/file_shim.cpp")
        .file("shim/tk_shim.cpp")
        .file("shim/picture_shim.cpp")
        .file("shim/xiph_shim.cpp")
        .file("shim/id3v1_shim.cpp")
        .file("shim/id3v2_shim.cpp")
        .file("shim/mp4_shim.cpp")
        .flag("-fexceptions")  // Make sure exceptions are enabled
        .flag("-frtti")       // Explicitly enable RTTI
        .include(format!("taglib/pkg/{}/include", target))
        .include(".") // Add the current directory to include path
        .flag_if_supported("-std=c++14");

    
    if is_android {
        builder.cpp_link_stdlib("c++_static"); // Use shared C++ runtime for Android compatibility
    } else {
        builder.cpp_link_stdlib("c++");
    }
    builder.compile("taglib_cxx_bindings");

    // Rebuild if shim files change
    println!("cargo:rerun-if-changed=shim/");
    println!("cargo:rerun-if-changed=taglib/");
```
