### ISSUE TITLE
Note in README and rustdoc that you need an "extern crate link_cplusplus"

### ISSUE THREAD

**Issue by PlasmaPower** [dtolnay/link-cplusplus#7]
In recent cargo versions, it seems the build script output will be ignored if the crate isn't used. I resolved this by adding `extern crate link_cplusplus;` to the `lib.rs`: https://github.com/MerosCrypto/meroxidizer/commit/dba349ad6838708c38bec64134190e7846f3367c

**Comment by dtolnay** [comment]
Thanks, good call. I've published a new version with better documentation.
